---
title: "Phylogeny"
author: "Silvana Lord Smits, Erik Demitz-Helin"
format:
  html:
    theme: cosmo
number-sections: true
toc: true
---

By now you should have downloaded and installed MEGA according to the instructions in [Practical 2: PLINK and MEGA Introduction](practicals/Practicals%20-%20Variant%20Calling/PRACTICAL_PLINK_MEGA_INTRO.qmd). You should also have had your lectures on phylogeny. The goal of these labs is to use MEGA, and some other resources, to learn how to carry out phylogenetic analyses in practice. The following instructions are based on a previous tutorial created by Magnus Alm Rosenblad for this course.

## Report
The lab is split up into two parts, but you will hand in one lab report. You will hand in a report that includes a title and your name, and is written as a full text. The report should give a brief introduction to the different datasets you are working with. You should also explain the different steps you performed, in such a way that someone who has not performed the same analysis can understand what you did. Include pictures of your trees in appendices with a figure legend. Mark relevant parts so it is easy for your reader to follow along. Make sure to provide answers to all questions in the instructions.

# Part 1 - Barnacles
In this part, you will learn how to carry out the different steps involved in a phylogenetic analysis. For your report, you will describe what data you have been working with, and what you have done. In your report you should display and evaluate your trees, in context of their robustness and evolution for this gene family.

You will be working with sequencing data from different barnacle species. Before this analysis, only the *A. amphitrite* WSP (`Ba_WSP`) protein sequence was available in public databases, but there were indications that there might be WSP paralogs in that species. The true number of this protein family is not known, so there is no clear answer to how they are related.

## Drawing a tree
To familiarize you with phylogenetic trees themselves, you will start by visualizing the tree shown to you in the introduction slides for the lab. This one is found in the file `phylo_tree.newick`. This is a new file format. You can open it with any text viewer to take a look at it. Newick files contain (phylogenetic) tree structures through the use of nested parentheses and commas. Leaves and nodes are defined by names, optionally with branch lengths, in a single line of text. 

Now load this tree file into MEGA.

::: {.callout-note}
Some names and a few values might be a bit different from the one on the slides.
:::

::: {.callout-tip}
# Question
Compare what you see to the text contents of `phylo_tree.newick`. Do you understand the format? How are the values for branch length and support written?
:::

## Modifying a tree
In the control panel, you can select a lot of different options. For instance, you can change the display of the tree in circular, rectangular and unrooted fashion. Try them out. You can also choose an outgroup and re-root the tree. To do this, you need to mark the branch you want to use as an outgroup. You can choose to add or leave out branch lengths, and change the display of your branches and labels. You can display the support values as well, and change how this is displayed. Clicking on specific branches (subtree), tips or nodes allows you to change their color, highlight blocks, etc. 

1. Root your tree using the cupin branch. This should make the tree look more like the one from the slides. 
2. Further rotate branches so it resembles the one from the slides even more. Don’t forget to include your support values. 
3. Color the branches for which the clades have both *A. improvisus* (`Bi`) and *A. amphitrite* (`Ba`) species.

::: {.callout-note}
Historically, both these species were part of the *Balanus* genus (hence the `B` prefix), but have since been re-calssified as part of the *Amphibalanus* genus.
:::

::: {.callout-tip}
# Question
How many of the genes seem to have been present in the ancestor of *A. improvisus* and *A. amphitrite*? 
:::

::: {.callout-tip}
# Question
Can you identify duplication events?
:::

## Phylogenetic analysis
You will now perform a phylogenic analysis yourself, with additional sequences. These analyses start by collecting sequences. These are usually kept in FASTA format, which you should be very familiar with by now. The set of sequences used to create the tree you used above is found in “phylo_sequences.faa’. Some more sequences were found that were not included in the analysis. These are in the file ‘phylo-2_moreseqs.faa’. 

Using this new dataset, you will now perform two analyses so you can compare them, and answer the questions below. You can choose which methods you want to you, or if you want to run the same method with different settings.

::: {.callout-note}
FASTA files (`.fasta`/`.fa`/`.faa`) files are just text files with a different extension, meaning you can change them before using them for an alignment, and open them in any basic text editor. So if you wish, you can change the identifier to make it more intuitive to you what type of sequence, and from which species, it is. Programs handle these identifiers in different ways. Some tools, like ClustalO, only keep the text until the first space in the header. So if you want to ensure specific information is kept, make sure that it is present in the beginning.
:::

### Multiple sequence alignment

Your analysis will begin by performing an alignment. You can do this in different ways. Most algorithms (MAFFT, MUSCLE and CLUSTALO, etc.) are avaiable as command line tools which you can run from the terminal. You can also use web based interfaces for these can also be found online, but because these run on shared servers they are often much slower than running on your own hardware. Lastly, MEGA itself can perform alignments using several different algorithms as well, providing a graphical interface while still running on your own computer. 
 
Either perform your alignment directly in MEGA here or upload your alignment results to MEGA afterwards.

::: {.callout-tip}
# Question
Take a look at your alignment in MEGA. Do you see more/less conserved regions already? How are they indicated? 
:::

### Substitution model testing
When using any tree-building algorithm, you will have the option to select which nt/aa substitution model to use. It can be difficult to pick a model, and which model will work best depends on your data. Luckily, MEGA provides a way to simplify model selection by benchmarking the relative performance of each model. Perform a model test to decide which one to use for your data.

::: {.callout-tip}
# Question
Which nt/aa substitution model suits your data best? Focus on the BIC scores, but other results might also be interesting. 
:::

### Molecular clock testing
MEGA has another nice feature we can use to answer the question ‘Does forcing all branches to evolve at the same rate significantly reduce how well the model explains the data?’. As you might remember from your lectures, some algorithms assume a constant evolutionary rate across all lineages, other have the option to use a (relaxed) clock, and other do not use it at all. It is one of many possible model constraints. Using the clock testing option in MEGA, we can be test the molecular clock assumption against our data using a likelihood ratio test. Try this out for your data. 

::: {.callout-tip}
# Question
What were the results of the test? What does that tell you?
:::

### Tree building
Next, you can build your actual tree. In MEGA, this is another convenient button on the startup screen. You can choose between a variety of methods, which you should remember from your phylogeny lectures. You can also play around with the settings for a specific method. 


### Visualization and interpreting results
Once you have finished both of your phylogenic analyses (using different substitution models, MSA or tree-building algorithms), use MEGA to look at the results. 

-	When rooting the tree, you don’t know where the new sequences ( cad-B-D) will end up. Is it then better to root the tree using all three ‘cup’ sequences, or only the ‘cup_Dp’, which is from a different phylogenetic group than Bi and Ba?
-	Explain in which clades the new sequences end up. Are new clades produced, or are the cand-B-D just added to the clades that you found before? Include clear visualizations of your results in your report. 
Extra (if you have time)

You can also try using an alignment of only the core region (‘phylo_moreseqs_core.fst’). All trees that you have made will be slightly different, and it may be hard to arrive at a conclusion about the evolution of these species, since we do not have a full genome for either *A. improvisus* or *A. amphitrite*. If you really want to spend time on this, you can go hunting for orhologs in other species, using NCBI BLASTP (limit your search to the *Balanidae* family if the results are overwhelming)

# Part 2 - SRP9
Now that you know how to carry out all the steps involved in a phylogenic analysis, you will perform a phylogenic analysis on the SRP9 protein. You will collect sequences, perform alignments and realignments to check your progress, and finish with performing two phylogenetic analyses (using two different methods for at least one analysis). Don’t forget to check which substitution model best suits your data, and molecular clock testing. 

Keep a table of all your included sequences to keep track of them. Include columns with their name, accession number, and the description for the original plus taxonomic group. That way you keep an overview of what you are doing. Include this table in the report.

## Building an initial tree
In this part you will be working with sequencing data from a conserved gene’s protein, SRP9, from different groups of animals (Metazoa). You are already provided with a couple of sequences in the file ‘lab2_sequences.faa’ to get you started. Look for NCBI Refseq sequences for SRP9 from different *Metazoa* species. You can search the NCBI protein database by using a query like `human[ORGN] SRP9` or `mouse[ORGN] SRP9`. You can append `refseq[filter]` to limit the search to only include refseq accessions.

In case you cannot find a Refseq protein for a species you would like to add, you can search the RNA databases (EST or TSA) using TBLASTN and predict the protein sequence. Just make sure the sequences have a match for the [SRP9-21 domain](https://www.ebi.ac.uk/interpro/entry/pfam/PF05486/).

::: {.callout-note}
When collecting sequences, remember you might want to change the identifier to keep track of the sequences you have. You might also want to add something to see which phylogenetic group they below to (e.g. `MV` for metazoan vertebrate).
:::

After collecting at least human, mouse, chicken, zebrafish, make a global alignment. Inspect your alignment to see if it looks okay.

::: {.callout-tip}
# Question
In the sequences you are provided with, there are two human isoforms. Based on the alignment, which isoform do you think you should keep?
:::

Make a new alignment after removing one of the human SRP9 isoforms, and see how many positions seem to contain a signal (not 100% conserved). In Clustal, positions with “*” under them have identical amino acids. As you add sequences, less and less positions will remain conserved. You can filter your initial alignment and check how much is left for the analysis. 

## Collecting more orthologs
Continue by adding a few more vertebrates (eg. *P. troglodytes*, *B. bombina*) and then the chordates (eg. *C. intestinalis*, *B. lanceolatum*). Inspect your alignment again. Add an echinoderm (eg. *S. purpuratus*, *F. indica*), and make a new tree. Keep adding species from different metazoan groups, (*Cnidaria*, *Placozoa*, *Arthropoda*, *Mollusca*, *Annelida*, ...). Finally, add the slime mold *D. mucoroides* as an outgroup.

## Species tree
The full lineage of the species you include in your analysis can be easily looked at using the NCBI taxonomy browser. Species trees can be built using NCBI’s Common Taxonomy Tree tool. Write the name of each of your species, and press ‘add’. Once you have included them all, save your results as a phylip tree, which can be opened in MEGA. This tree should also be included in the report.

::: {.callout-tip}
# Question
Compare the species tree to your final SRP9 sequence tree. Does it look similar? What are the differences?
:::





